const CREATE_ANNOUNCEMENT_PENDING = "CREATE_ANNOUNCEMENT_PENDING";
const CREATE_ANNOUNCEMENT_SUCCESS = "CREATE_ANNOUNCEMENT_SUCCESS";
const CREATE_ANNOUNCEMENT_ERROR = "CREATE_ANNOUNCEMENT_ERROR";

const GET_ALL_ANNOUNCEMENTS_PENDING = "GET_ALL_ANNOUNCEMENTS_PENDING";
const GET_ALL_ANNOUNCEMENTS_SUCCESS = "GET_ALL_ANNOUNCEMENTS_SUCCESS";
const GET_ALL_ANNOUNCEMENTS_ERROR = "GET_ALL_ANNOUNCEMENTS_ERROR";

const GET_ANNOUNCEMENT_PENDING = "GET_ANNOUNCEMENT_PENDING";
const GET_ANNOUNCEMENT_SUCCESS = "GET_ANNOUNCEMENT_SUCCESS";
const GET_ANNOUNCEMENT_ERROR = "GET_ANNOUNCEMENT_ERROR";

export {
  CREATE_ANNOUNCEMENT_PENDING,
  CREATE_ANNOUNCEMENT_SUCCESS,
  CREATE_ANNOUNCEMENT_ERROR,
  GET_ALL_ANNOUNCEMENTS_PENDING,
  GET_ALL_ANNOUNCEMENTS_SUCCESS,
  GET_ALL_ANNOUNCEMENTS_ERROR,
  GET_ANNOUNCEMENT_PENDING,
  GET_ANNOUNCEMENT_SUCCESS,
  GET_ANNOUNCEMENT_ERROR,
};
