const GET_All_CATEGORY_PENDING = "GET_All_CATEGORY_PENDING";
const GET_All_CATEGORY_SUCCESS = "GET_All_CATEGORY_SUCCESS";
const GET_All_CATEGORY_ERROR = "GET_All_CATEGORY_ERROR";

export {
  GET_All_CATEGORY_PENDING,
  GET_All_CATEGORY_SUCCESS,
  GET_All_CATEGORY_ERROR,
};
