const GET_ALL_CITIES_PENDING = "GET_ALL_CITIES_PENDING";
const GET_ALL_CITIES_SUCCESS = "GET_ALL_CITIES_SUCCESS";
const GET_ALL_CITIES_ERROR = "GET_ALL_CITIES_ERROR";

const GET_CITY_PENDING = "GET_CITY_PENDING";
const GET_CITY_SUCCESS = "GET_CITY_SUCCESS";
const GET_CITY_ERROR = "GET_CITY_ERROR";

export {
  GET_ALL_CITIES_PENDING,
  GET_ALL_CITIES_SUCCESS,
  GET_ALL_CITIES_ERROR,
  GET_CITY_PENDING,
  GET_CITY_SUCCESS,
  GET_CITY_ERROR,
};
