const POST_CONTACT_PENDING = "POST_CONTACT_PENDING";
const POST_CONTACT_SUCCESS = "POST_CONTACT_SUCCESS";
const POST_CONTACT_ERROR = "POST_CONTACT_ERROR";

export { POST_CONTACT_PENDING, POST_CONTACT_SUCCESS, POST_CONTACT_ERROR };
