const POST_SUBSCRIBE_PENDING = "POST_SUBSCRIBE_PENDING";
const POST_SUBSCRIBE_SUCCESS = "POST_SUBSCRIBE_SUCCESS";
const POST_SUBSCRIBE_ERROR = "POST_SUBSCRIBE_ERROR";

export { POST_SUBSCRIBE_PENDING, POST_SUBSCRIBE_SUCCESS, POST_SUBSCRIBE_ERROR };
