const GET_USER_PENDING = "GET_USER_PENDING";
const GET_USER_SUCCESS = "GET_USER_SUCCESS";
const GET_USER_ERROR = "GET_USER_ERROR";
const UPDATE_USER_PENDING = "UPDATE_USER_PENDING";
const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export {
  GET_USER_PENDING,
  GET_USER_SUCCESS,
  GET_USER_ERROR,
  UPDATE_USER_PENDING,
  UPDATE_USER_SUCCESS,
  UPDATE_USER_ERROR,
};
